defmodule AllbertAssist.DynamicPlugins.Staging do
  @moduledoc """
  Builds disposable project-shaped staging trees for v0.37 dynamic drafts.

  The staging tree is outside Allbert Home and has no authority by itself. It
  exists only so generated files can be placed on the same compile-visible paths
  that the v0.36 sandbox gate will later copy into `/workspace/project`.
  """

  alias AllbertAssist.DynamicPlugins.Draft
  alias AllbertAssist.DynamicPlugins.MetadataStore
  alias AllbertAssist.Sandbox.SourcePolicy
  alias AllbertAssist.Settings

  @allowed_project_extensions ~w[.app .config .ex .exs .eex .heex .erl .hrl .json .lock .md .yml .yaml]
  @blocked_project_segments ~w[.git _build deps node_modules priv/static assets vendor .elixir_ls]
  @source_prefix ~w[apps allbert_assist lib allbert_assist dynamic_plugins generated]
  @test_prefix ~w[apps allbert_assist test allbert_assist dynamic_plugins generated]

  @enforce_keys [:id, :root, :project_root, :draft, :generated_files]
  defstruct @enforce_keys ++
              [
                project_files: [],
                focused_test_paths: [],
                security_eval_paths: nil,
                diagnostics: []
              ]

  @type t :: %__MODULE__{
          id: String.t(),
          root: String.t(),
          project_root: String.t(),
          draft: Draft.t(),
          generated_files: [map()],
          project_files: [map()],
          focused_test_paths: [String.t()],
          security_eval_paths: [String.t()] | nil,
          diagnostics: [map()]
        }

  @doc "Build a staged project tree from one persisted draft."
  @spec build(Draft.t(), keyword()) :: {:ok, t()} | {:error, term()}
  def build(%Draft{} = draft, opts \\ []) do
    with {:ok, manifest} <- MetadataStore.get_manifest(draft.slug),
         {:ok, entries} <- manifest_entries(manifest, draft),
         :ok <- enforce_metadata_contract(draft, entries),
         {:ok, project_root} <- project_root(opts),
         {:ok, root} <- allocate_root(draft, opts),
         :ok <- reject_allbert_home_root(root),
         :ok <- File.mkdir_p(root),
         {:ok, project_files} <- copy_project(project_root, root, opts),
         {:ok, generated_files} <- materialize_generated_files(draft, entries, root),
         :ok <- enforce_generated_limits(generated_files),
         :ok <- scan_generated_files(generated_files) do
      {:ok,
       %__MODULE__{
         id: Path.basename(root),
         root: root,
         project_root: project_root,
         draft: draft,
         generated_files: generated_files,
         project_files: project_files,
         focused_test_paths: focused_test_paths(manifest, generated_files),
         security_eval_paths: optional_string_list(manifest, "security_eval_paths")
       }}
    else
      {:error, reason} -> {:error, reason}
    end
  rescue
    exception ->
      {:error, {:staging_failed, exception.__struct__, Exception.message(exception)}}
  end

  @doc "Return bundle params that force generated bytes through v0.36 scan mounts."
  @spec bundle_params(t()) :: map()
  def bundle_params(%__MODULE__{} = staging) do
    %{
      project_root: staging.root,
      draft_paths: generated_source_paths(staging),
      test_paths: generated_test_paths(staging),
      id: "dynamic-#{staging.draft.slug}-#{System.unique_integer([:positive])}"
    }
  end

  @doc "Return a bounded staging summary for draft metadata and action output."
  @spec summary(t()) :: map()
  def summary(%__MODULE__{} = staging) do
    %{
      id: staging.id,
      project_root: staging.project_root,
      generated_file_count: length(staging.generated_files),
      generated_paths: Enum.map(staging.generated_files, & &1.compiled_path),
      focused_test_paths: staging.focused_test_paths,
      security_eval_paths: staging.security_eval_paths
    }
  end

  defp manifest_entries(manifest, %Draft{} = draft) when is_map(manifest) do
    source_values = list_entries(manifest, ["files", "source_files"])
    test_values = list_entries(manifest, ["tests", "test_files"])

    with {:ok, source_entries} <- entries(source_values, :source, draft),
         {:ok, test_entries} <- entries(test_values, :test, draft) do
      entries = source_entries ++ test_entries

      if entries == [] do
        {:error, :draft_manifest_empty}
      else
        {:ok, entries}
      end
    end
  end

  defp list_entries(manifest, keys) do
    keys
    |> Enum.find_value([], fn key ->
      case Map.get(manifest, key) || Map.get(manifest, String.to_atom(key), nil) do
        values when is_list(values) -> values
        _other -> nil
      end
    end)
  end

  defp entries(entries, kind, draft) do
    Enum.reduce_while(entries, {:ok, []}, fn entry, {:ok, acc} ->
      entry = %{
        kind: kind,
        source_path: source_path(entry),
        compiled_path: compiled_path(entry)
      }

      case validate_entry(entry, draft) do
        {:ok, entry} -> {:cont, {:ok, [entry | acc]}}
        {:error, reason} -> {:halt, {:error, {:invalid_manifest_entry, reason}}}
      end
    end)
    |> case do
      {:ok, entries} -> {:ok, Enum.reverse(entries)}
      error -> error
    end
  end

  defp source_path(entry) when is_map(entry) do
    Map.get(entry, "source_path") || Map.get(entry, :source_path) ||
      Map.get(entry, "source") || Map.get(entry, :source)
  end

  defp compiled_path(entry) when is_map(entry) do
    Map.get(entry, "compiled_path") || Map.get(entry, :compiled_path) ||
      Map.get(entry, "target_path") || Map.get(entry, :target_path) ||
      Map.get(entry, "compiled") || Map.get(entry, :compiled)
  end

  defp validate_entry(%{source_path: source_path, compiled_path: compiled_path} = entry, draft) do
    with :ok <- validate_relative_path(source_path, :source_path),
         :ok <- validate_relative_path(compiled_path, :compiled_path),
         :ok <- validate_compiled_path(entry.kind, draft.slug, compiled_path) do
      {:ok, entry}
    end
  end

  defp validate_relative_path(path, field) when is_binary(path) do
    cond do
      String.trim(path) == "" ->
        {:error, {field, :empty}}

      Path.type(path) != :relative ->
        {:error, {field, :absolute}}

      ".." in Path.split(path) ->
        {:error, {field, :traversal}}

      true ->
        :ok
    end
  end

  defp validate_relative_path(path, field), do: {:error, {field, {:invalid, path}}}

  defp validate_compiled_path(:source, slug, path) do
    validate_generated_path(path, @source_prefix ++ [slug], ".ex")
  end

  defp validate_compiled_path(:test, slug, path) do
    validate_generated_path(path, @test_prefix ++ [slug], ".exs")
  end

  defp validate_generated_path(path, prefix, extension) do
    segments = Path.split(path)

    cond do
      Enum.take(segments, length(prefix)) != prefix ->
        {:error, {:compiled_path_outside_generated_namespace, path}}

      Path.extname(path) != extension ->
        {:error, {:compiled_path_extension, path, extension}}

      true ->
        :ok
    end
  end

  defp enforce_metadata_contract(%Draft{} = draft, entries) do
    source_paths = entries |> Enum.map(& &1.source_path) |> MapSet.new()
    compiled_paths = entries |> Enum.map(& &1.compiled_path) |> MapSet.new()
    scan_paths = MapSet.new(draft.scan_paths)
    source_hash_paths = draft.source_hashes |> Map.keys() |> MapSet.new()
    declared_compiled_paths = MapSet.new(draft.compiled_paths)

    cond do
      not MapSet.subset?(source_paths, source_hash_paths) ->
        {:error,
         {:unscanned_compile_path,
          MapSet.difference(source_paths, source_hash_paths) |> sorted_set()}}

      not MapSet.subset?(source_hash_paths, source_paths) ->
        {:error,
         {:scanned_but_not_compiled,
          MapSet.difference(source_hash_paths, source_paths) |> sorted_set()}}

      scan_paths != source_paths ->
        {:error,
         {:scan_path_mismatch,
          %{expected: sorted_set(source_paths), actual: sorted_set(scan_paths)}}}

      declared_compiled_paths != compiled_paths ->
        {:error,
         {:compiled_path_mismatch,
          %{expected: sorted_set(compiled_paths), actual: sorted_set(declared_compiled_paths)}}}

      true ->
        :ok
    end
  end

  defp sorted_set(set), do: set |> MapSet.to_list() |> Enum.sort()

  defp project_root(opts) do
    root = opts |> Keyword.get(:project_root, File.cwd!()) |> Path.expand()

    if File.dir?(root) do
      {:ok, root}
    else
      {:error, {:project_root_missing, root}}
    end
  end

  defp allocate_root(%Draft{} = draft, opts) do
    case Keyword.get(opts, :staging_root) do
      nil ->
        root =
          Path.join(
            System.tmp_dir!(),
            "allbert-dynamic-stage-#{draft.slug}-#{System.unique_integer([:positive])}"
          )

        {:ok, root}

      root when is_binary(root) ->
        root = Path.expand(root)

        if File.exists?(root) do
          {:error, {:staging_root_exists, root}}
        else
          {:ok, root}
        end

      other ->
        {:error, {:invalid_staging_root, other}}
    end
  end

  defp reject_allbert_home_root(root) do
    home = Path.expand(AllbertAssist.Paths.home())
    root = Path.expand(root)

    if root == home or String.starts_with?(root, home <> "/") do
      {:error, :staging_root_inside_allbert_home}
    else
      :ok
    end
  end

  defp copy_project(project_root, root, opts) do
    inputs = Keyword.get(opts, :project_paths, default_project_inputs(project_root))

    inputs
    |> Enum.reduce_while({:ok, []}, fn input, {:ok, acc} ->
      case copy_project_input(project_root, root, input) do
        {:ok, entries} -> {:cont, {:ok, acc ++ entries}}
        {:error, reason} -> {:halt, {:error, reason}}
      end
    end)
    |> case do
      {:ok, entries} -> {:ok, Enum.uniq_by(entries, & &1.relative)}
      error -> error
    end
  end

  defp default_project_inputs(project_root) do
    [
      "mix.exs",
      "mix.lock",
      ".formatter.exs",
      ".credo.exs",
      ".dialyzer_ignore.exs",
      "config",
      "apps",
      "plugins"
    ]
    |> Enum.filter(&File.exists?(Path.join(project_root, &1)))
  end

  defp copy_project_input(project_root, root, input) when is_binary(input) do
    source = Path.expand(input, project_root)

    with :ok <- validate_project_input(project_root, source) do
      cond do
        File.regular?(source) -> copy_project_file(project_root, root, source)
        File.dir?(source) -> copy_project_directory(project_root, root, source)
        true -> {:error, {:project_input_missing, input}}
      end
    end
  end

  defp copy_project_input(_project_root, _root, input),
    do: {:error, {:invalid_project_input, input}}

  defp copy_project_directory(project_root, root, source) do
    source
    |> Path.join("**/*")
    |> Path.wildcard(match_dot: true)
    |> Enum.reject(&File.dir?/1)
    |> Enum.reduce_while({:ok, []}, fn file, {:ok, acc} ->
      case copy_project_file(project_root, root, file) do
        {:ok, []} -> {:cont, {:ok, acc}}
        {:ok, [entry]} -> {:cont, {:ok, [entry | acc]}}
        {:error, reason} -> {:halt, {:error, reason}}
      end
    end)
    |> case do
      {:ok, entries} -> {:ok, Enum.reverse(entries)}
      error -> error
    end
  end

  defp copy_project_file(project_root, root, source) do
    relative = Path.relative_to(source, project_root)

    cond do
      blocked_project_path?(relative) ->
        {:ok, []}

      Path.extname(source) not in @allowed_project_extensions ->
        {:ok, []}

      symlink?(source) ->
        {:error, {:symlink_not_allowed, relative}}

      true ->
        target = Path.join(root, relative)
        File.mkdir_p!(Path.dirname(target))
        File.cp!(source, target)

        {:ok,
         [%{source: source, target: target, relative: relative, bytes: File.stat!(source).size}]}
    end
  end

  defp validate_project_input(project_root, source) do
    cond do
      not same_or_inside?(source, project_root) ->
        {:error, {:project_input_outside_root, source}}

      symlink?(source) ->
        {:error, {:symlink_not_allowed, Path.relative_to(source, project_root)}}

      true ->
        :ok
    end
  end

  defp materialize_generated_files(%Draft{} = draft, entries, root) do
    draft_root = draft.root || MetadataStore.draft_root(draft.slug)

    entries
    |> Enum.reduce_while({:ok, []}, fn entry, {:ok, acc} ->
      case materialize_generated_file(draft, draft_root, root, entry) do
        {:ok, file} -> {:cont, {:ok, [file | acc]}}
        {:error, reason} -> {:halt, {:error, reason}}
      end
    end)
    |> case do
      {:ok, files} -> {:ok, Enum.reverse(files)}
      error -> error
    end
  end

  defp materialize_generated_file(%Draft{} = draft, draft_root, root, entry) do
    with {:ok, source} <- safe_join(draft_root, entry.source_path),
         :ok <- validate_generated_source(source, entry.source_path),
         {:ok, expected_hash} <- fetch_expected_hash(draft, entry.source_path),
         {:ok, source_hash} <- MetadataStore.hash_file(source),
         :ok <- verify_hash(entry.source_path, expected_hash, source_hash),
         {:ok, target} <- safe_join(root, entry.compiled_path),
         :ok <- reject_existing_target(target, entry.compiled_path) do
      File.mkdir_p!(Path.dirname(target))
      File.cp!(source, target)

      with {:ok, staged_hash} <- MetadataStore.hash_file(target),
           :ok <- verify_hash(entry.compiled_path, expected_hash, staged_hash) do
        {:ok,
         %{
           kind: entry.kind,
           source_path: entry.source_path,
           compiled_path: entry.compiled_path,
           source: source,
           target: target,
           hash: expected_hash,
           bytes: File.stat!(target).size
         }}
      end
    end
  end

  defp validate_generated_source(source, relative) do
    cond do
      symlink?(source) ->
        {:error, {:symlink_not_allowed, relative}}

      not File.regular?(source) ->
        {:error, {:generated_source_missing, relative}}

      true ->
        :ok
    end
  end

  defp fetch_expected_hash(%Draft{} = draft, path) do
    case Map.fetch(draft.source_hashes, path) do
      {:ok, hash} -> {:ok, hash}
      :error -> {:error, {:source_hash_missing, path}}
    end
  end

  defp verify_hash(_path, hash, hash), do: :ok

  defp verify_hash(path, expected, actual),
    do: {:error, {:source_hash_mismatch, path, expected, actual}}

  defp reject_existing_target(target, relative) do
    if File.exists?(target) do
      {:error, {:compiled_path_already_exists, relative}}
    else
      :ok
    end
  end

  defp enforce_generated_limits(generated_files) do
    total_bytes = generated_files |> Enum.map(& &1.bytes) |> Enum.sum()

    cond do
      length(generated_files) > setting("dynamic_codegen.max_files", 32) ->
        {:error, {:generated_file_count_exceeded, length(generated_files)}}

      total_bytes > setting("dynamic_codegen.max_bytes", 262_144) ->
        {:error, {:generated_bytes_exceeded, total_bytes}}

      true ->
        :ok
    end
  end

  defp scan_generated_files(generated_files) do
    generated_files
    |> Enum.map(& &1.target)
    |> SourcePolicy.scan()
    |> case do
      {:ok, _report} -> :ok
      {:error, report} -> {:error, {:source_policy_denied, report.diagnostics}}
    end
  end

  defp generated_source_paths(%__MODULE__{} = staging) do
    staging.generated_files
    |> Enum.filter(&(&1.kind == :source))
    |> Enum.map(& &1.compiled_path)
  end

  defp generated_test_paths(%__MODULE__{} = staging) do
    staging.generated_files
    |> Enum.filter(&(&1.kind == :test))
    |> Enum.map(& &1.compiled_path)
  end

  defp focused_test_paths(manifest, generated_files) do
    manifest
    |> optional_string_list("focused_test_paths")
    |> case do
      nil ->
        generated_files
        |> Enum.filter(&(&1.kind == :test))
        |> Enum.map(& &1.compiled_path)

      paths ->
        paths
    end
  end

  defp optional_string_list(manifest, key) do
    case Map.get(manifest, key) || Map.get(manifest, String.to_atom(key), nil) do
      values when is_list(values) ->
        if Enum.all?(values, &is_binary/1), do: values, else: nil

      _other ->
        nil
    end
  end

  defp safe_join(root, relative_path) do
    root = Path.expand(root)
    path = Path.expand(Path.join(root, relative_path))

    if path == root or String.starts_with?(path, root <> "/") do
      {:ok, path}
    else
      {:error, {:path_outside_root, relative_path}}
    end
  end

  defp setting(key, default) do
    case Settings.get(key) do
      {:ok, value} when is_integer(value) -> value
      _other -> default
    end
  end

  defp blocked_project_path?(relative) do
    relative
    |> Path.split()
    |> Enum.any?(&(&1 in @blocked_project_segments))
  end

  defp symlink?(path) do
    case File.lstat(path) do
      {:ok, %{type: :symlink}} -> true
      _other -> false
    end
  end

  defp same_or_inside?(path, root) do
    path = Path.expand(path)
    root = Path.expand(root)

    path == root or String.starts_with?(path, root <> "/")
  end
end
