defmodule StockSage.Plugin do
  @moduledoc """
  StockSage plugin entrypoint.

  The plugin contributes contract data only. Registration does not grant
  permissions, start analysis execution, or load code dynamically.
  """

  use AllbertAssist.Plugin

  @impl true
  def plugin_id, do: "stocksage"

  @impl true
  def display_name, do: "StockSage"

  @impl true
  def version, do: "0.35.0"

  @impl true
  def validate(_opts), do: :ok

  @impl true
  def apps, do: [StockSage.App]

  @impl true
  def actions do
    [
      StockSage.Actions.ListAnalyses,
      StockSage.Actions.ShowAnalysis,
      StockSage.Actions.GetTrends,
      StockSage.Actions.ResolveOutcomes,
      StockSage.Actions.GenerateReflection,
      StockSage.Actions.QueueAnalysis,
      StockSage.Actions.ListQueue,
      StockSage.Actions.ImportSqlite,
      StockSage.Actions.RunAnalysis,
      StockSage.Actions.Agents.ListAgents,
      StockSage.Actions.Agents.ShowAgent,
      StockSage.Actions.Evidence.FetchMarketData,
      StockSage.Actions.Evidence.FetchNews,
      StockSage.Actions.Evidence.FetchSentiment,
      StockSage.Actions.Evidence.FetchFundamentals,
      StockSage.Actions.Evidence.FetchFinancials
    ]
  end

  @impl true
  def skill_paths do
    # v1.4 M13: an extracted pack addresses its own assets through its
    # application, not the `plugins/<id>/` convention. Skills moved under `priv/`
    # for the same reason the notes_files pack's did at M9 -- that is the tree an
    # OTP release ships, and `Application.app_dir/2` resolves it identically in a
    # checkout and in a packaged artifact.
    [Application.app_dir(:stocksage, "priv/skills")]
  end

  # v1.4 M13: settings ownership moved to StockSage.SettingsFragment, a pack
  # FragmentOwner declared by StockSage.Pack.settings_fragments/0. Returning the
  # schema here as well would produce the same fragment id twice and fail
  # composition with :duplicate_settings_fragment_id. The schema itself did not
  # move -- StockSage.Settings.Fragment is still its only definition.
  @impl true
  def settings_schema, do: []

  @impl true
  # Return the supervisor's auto-generated child_spec map rather than the
  # `{module, args}` shorthand. The shorthand works at runtime (the
  # supervisor expands it) but mismatches `AllbertAssist.Plugin`'s
  # `child_spec/1` callback typespec, which expects a Supervisor.child_spec
  # map or `:ignore`. Dialyzer flagged the tuple form; this delegates to
  # `StockSage.Supervisor.child_spec/1` (auto-generated by `use Supervisor`)
  # so the returned value satisfies the typespec.
  def child_spec(opts), do: StockSage.Supervisor.child_spec(opts)
end
