defmodule UpdateFixture do
  def run() do
    fixture_path = "/Users/spuri/projects/lexlapax/allbert-assist/apps/allbert_assist/test/fixtures/v1.4/m1a3_effect_boundaries.json"

    fixture = fixture_path
    |> File.read!()
    |> Jason.decode!()

    updated = fixture
    |> Map.put("expected_effect_guard_sources", effect_guard_sources())
    |> Map.put("expected_activation_guard_sources", activation_guard_sources())
    |> Map.put("expected_epoch_sources", epoch_sources())
    |> Map.put("expected_activation_rejection_sources", activation_rejection_sources())

    json = Jason.encode!(updated, pretty: true)
    File.write!(fixture_path, json)

    IO.puts("Fixture updated successfully")
    IO.puts("Effect Guard sources: #{length(effect_guard_sources())}")
    IO.puts("Activation Guard sources: #{length(activation_guard_sources())}")
    IO.puts("Epoch sources: #{length(epoch_sources())}")
    IO.puts("Activation rejection sources: #{length(activation_rejection_sources())}")
  end

  defp effect_guard_sources do
    [
      "apps/allbert_assist/lib/allbert_assist/actions/first_model/pull_model.ex",
      "apps/allbert_assist/lib/allbert_assist/actions/image/generate_image.ex",
      "apps/allbert_assist/lib/allbert_assist/agents/intent_agent.ex",
      "apps/allbert_assist/lib/allbert_assist/app/registry.ex",
      "apps/allbert_assist/lib/allbert_assist/channels.ex",
      "apps/allbert_assist/lib/allbert_assist/channels/notify.ex",
      "apps/allbert_assist/lib/allbert_assist/channels/notify_consumer.ex",
      "apps/allbert_assist/lib/allbert_assist/cli.ex",
      "apps/allbert_assist/lib/allbert_assist/cli/areas.ex",
      "apps/allbert_assist/lib/allbert_assist/cli/areas/channels.ex",
      "apps/allbert_assist/lib/allbert_assist/cli/ask.ex",
      "apps/allbert_assist/lib/allbert_assist/cli/channels/support.ex",
      "apps/allbert_assist/lib/allbert_assist/confirmations/store/agent.ex",
      "apps/allbert_assist/lib/allbert_assist/confirmations/store/persistence.ex",
      "apps/allbert_assist/lib/allbert_assist/conversations.ex",
      "apps/allbert_assist/lib/allbert_assist/dev_gates/v13_fanout_eval.ex",
      "apps/allbert_assist/lib/allbert_assist/dev_gates/v13_zero_shot_eval.ex",
      "apps/allbert_assist/lib/allbert_assist/dynamic_plugins/reconciler.ex",
      "apps/allbert_assist/lib/allbert_assist/execution/process_owner.ex",
      "apps/allbert_assist/lib/allbert_assist/external/http_client.ex",
      "apps/allbert_assist/lib/allbert_assist/first_model/ollama.ex",
      "apps/allbert_assist/lib/allbert_assist/intent/router/index.ex",
      "apps/allbert_assist/lib/allbert_assist/jobs/runner.ex",
      "apps/allbert_assist/lib/allbert_assist/jobs/scheduler/agent.ex",
      "apps/allbert_assist/lib/allbert_assist/jobs/scheduler/commands.ex",
      "apps/allbert_assist/lib/allbert_assist/jobs/scheduler/executor.ex",
      "apps/allbert_assist/lib/allbert_assist/memory/projection.ex",
      "apps/allbert_assist/lib/allbert_assist/objectives.ex",
      "apps/allbert_assist/lib/allbert_assist/objectives/commands.ex",
      "apps/allbert_assist/lib/allbert_assist/objectives/fanout/report_composer.ex",
      "apps/allbert_assist/lib/allbert_assist/objectives/fanout/terminal_transitions.ex",
      "apps/allbert_assist/lib/allbert_assist/objectives/runs/coordinator.ex",
      "apps/allbert_assist/lib/allbert_assist/objectives/runs/scheduler.ex",
      "apps/allbert_assist/lib/allbert_assist/plugin/registry.ex",
      "apps/allbert_assist/lib/allbert_assist/public_protocol/acp/server.ex",
      "apps/allbert_assist/lib/allbert_assist/public_protocol/mcp/runtime.ex",
      "apps/allbert_assist/lib/allbert_assist/public_protocol/mcp/server.ex",
      "apps/allbert_assist/lib/allbert_assist/public_protocol/mcp/stdio_server.ex",
      "apps/allbert_assist/lib/allbert_assist/public_protocol/result_readback_sweeper.ex",
      "apps/allbert_assist/lib/allbert_assist/runtime.ex",
      "apps/allbert_assist/lib/allbert_assist/runtime/attach.ex",
      "apps/allbert_assist/lib/allbert_assist/search/projection.ex",
      "apps/allbert_assist/lib/allbert_assist/settings.ex",
      "apps/allbert_assist/lib/allbert_assist/settings/model_doctor.ex",
      "apps/allbert_assist/lib/allbert_assist/skills/direct_import.ex",
      "apps/allbert_assist/lib/allbert_assist/skills/online/registry_client.ex",
      "apps/allbert_assist/lib/allbert_assist/voice/local_runtime/backends/ollama_stt.ex",
      "apps/allbert_assist/lib/allbert_assist/voice/provider_http.ex",
      "apps/allbert_assist/lib/mix/tasks/allbert.ask.ex",
      "apps/allbert_assist/lib/mix/tasks/allbert.delegate.ex",
      "apps/allbert_email/lib/allbert_email/adapter.ex",
      "apps/allbert_email/lib/allbert_email/cli.ex",
      "apps/allbert_kernel/lib/allbert_assist/actions/runner.ex",
      "apps/allbert_telegram/lib/allbert_telegram/adapter.ex",
      "apps/allbert_telegram/lib/allbert_telegram/cli.ex",
      "apps/allbert_telegram/lib/allbert_telegram/client.ex",
      "plugins/allbert.artifacts/lib/mix/tasks/allbert.artifacts.ex",
      "plugins/allbert.browser/lib/allbert_browser/actions/start_session.ex",
      "plugins/allbert.browser/lib/allbert_browser/session.ex",
      "plugins/allbert.browser/lib/mix/tasks/allbert.browser.ex",
      "plugins/allbert.discord/lib/allbert_assist/channels/discord/adapter.ex",
      "plugins/allbert.discord/lib/allbert_assist/channels/discord/client.ex",
      "plugins/allbert.matrix/lib/allbert_assist/channels/matrix/adapter.ex",
      "plugins/allbert.matrix/lib/allbert_assist/channels/matrix/client.ex",
      "plugins/allbert.research/lib/allbert_research/delegate_objective.ex",
      "plugins/allbert.research/lib/mix/tasks/allbert.research.ex",
      "plugins/allbert.signal/lib/allbert_assist/channels/signal/adapter.ex",
      "plugins/allbert.signal/lib/allbert_assist/channels/signal/client.ex",
      "plugins/allbert.slack/lib/allbert_assist/channels/slack/adapter.ex",
      "plugins/allbert.slack/lib/allbert_assist/channels/slack/client.ex",
      "plugins/allbert.tui/lib/allbert_assist/channels/tui/adapter.ex",
      "plugins/allbert.whatsapp/lib/allbert_assist/channels/whatsapp/adapter.ex",
      "plugins/allbert.whatsapp/lib/allbert_assist/channels/whatsapp/client.ex",
      "plugins/stocksage/lib/mix/tasks/stocksage.agents.ex",
      "plugins/stocksage/lib/mix/tasks/stocksage.analyses.ex",
      "plugins/stocksage/lib/mix/tasks/stocksage.analyze.ex",
      "plugins/stocksage/lib/mix/tasks/stocksage.import_sqlite.ex",
      "plugins/stocksage/lib/mix/tasks/stocksage.queue.ex"
    ]
  end

  defp activation_guard_sources do
    [
      "apps/allbert_assist/lib/allbert_assist/app/registry.ex",
      "apps/allbert_assist/lib/allbert_assist/first_model/ollama.ex",
      "apps/allbert_assist/lib/allbert_assist/first_run/enablement/boot_worker.ex",
      "apps/allbert_assist/lib/allbert_assist/pack/activation_gate.ex",
      "apps/allbert_assist/lib/allbert_assist/pack/residual_effect_supervisor.ex",
      "apps/allbert_assist/lib/allbert_assist/pack/staged_children.ex",
      "apps/allbert_assist/lib/allbert_assist/plugin/bootstrap.ex"
    ]
  end

  defp epoch_sources do
    [
      "apps/allbert_assist/lib/allbert_assist/actions/channels/configure_channel_secret.ex",
      "apps/allbert_assist/lib/allbert_assist/actions/channels/configure_channel_setting.ex",
      "apps/allbert_assist/lib/allbert_assist/actions/channels/matrix_doctor.ex",
      "apps/allbert_assist/lib/allbert_assist/actions/coding/bash.ex",
      "apps/allbert_assist/lib/allbert_assist/actions/first_model/pull_model.ex",
      "apps/allbert_assist/lib/allbert_assist/actions/image/generate_image.ex",
      "apps/allbert_assist/lib/allbert_assist/actions/intent/external_network_request.ex",
      "apps/allbert_assist/lib/allbert_assist/actions/intent/run_shell_command.ex",
      "apps/allbert_assist/lib/allbert_assist/actions/jobs/run_job.ex",
      "apps/allbert_assist/lib/allbert_assist/actions/objectives/cancel_objective.ex",
      "apps/allbert_assist/lib/allbert_assist/actions/objectives/cancel_objective_run.ex",
      "apps/allbert_assist/lib/allbert_assist/actions/objectives/continue_objective.ex",
      "apps/allbert_assist/lib/allbert_assist/actions/objectives/delegate_agent.ex",
      "apps/allbert_assist/lib/allbert_assist/actions/objectives/steer_objective_run.ex",
      "apps/allbert_assist/lib/allbert_assist/actions/packages/run_package_install.ex",
      "apps/allbert_assist/lib/allbert_assist/actions/resources/revoke_resource_grant.ex",
      "apps/allbert_assist/lib/allbert_assist/actions/settings/apply_persona_profile.ex",
      "apps/allbert_assist/lib/allbert_assist/actions/settings/set_active_model_profile.ex",
      "apps/allbert_assist/lib/allbert_assist/actions/settings/set_direct_answer_model_profile.ex",
      "apps/allbert_assist/lib/allbert_assist/actions/settings/set_notes_root.ex",
      "apps/allbert_assist/lib/allbert_assist/actions/settings/set_provider_credential.ex",
      "apps/allbert_assist/lib/allbert_assist/actions/settings/update_setting.ex",
      "apps/allbert_assist/lib/allbert_assist/actions/skills/run_skill_script.ex",
      "apps/allbert_assist/lib/allbert_assist/actions/surface_policy/update.ex",
      "apps/allbert_assist/lib/allbert_assist/actions/voice/local_runtime_doctor.ex",
      "apps/allbert_assist/lib/allbert_assist/actions/voice/synthesize_voice.ex",
      "apps/allbert_assist/lib/allbert_assist/actions/voice/transcribe_voice.ex",
      "apps/allbert_assist/lib/allbert_assist/actions/workspace/set_theme.ex",
      "apps/allbert_assist/lib/allbert_assist/agents/intent_agent.ex",
      "apps/allbert_assist/lib/allbert_assist/app/registry.ex",
      "apps/allbert_assist/lib/allbert_assist/channels.ex",
      "apps/allbert_assist/lib/allbert_assist/channels/confirmation_callback.ex",
      "apps/allbert_assist/lib/allbert_assist/channels/notify.ex",
      "apps/allbert_assist/lib/allbert_assist/channels/notify_consent_callback.ex",
      "apps/allbert_assist/lib/allbert_assist/channels/notify_consumer.ex",
      "apps/allbert_assist/lib/allbert_assist/cli.ex",
      "apps/allbert_assist/lib/allbert_assist/cli/area.ex",
      "apps/allbert_assist/lib/allbert_assist/cli/areas.ex",
      "apps/allbert_assist/lib/allbert_assist/cli/areas/channels.ex",
      "apps/allbert_assist/lib/allbert_assist/cli/areas/jobs.ex",
      "apps/allbert_assist/lib/allbert_assist/cli/areas/memory.ex",
      "apps/allbert_assist/lib/allbert_assist/cli/areas/objectives.ex",
      "apps/allbert_assist/lib/allbert_assist/cli/areas/onboarding.ex",
      "apps/allbert_assist/lib/allbert_assist/cli/areas/plan.ex",
      "apps/allbert_assist/lib/allbert_assist/cli/areas/sessions.ex",
      "apps/allbert_assist/lib/allbert_assist/cli/areas/skills.ex",
      "apps/allbert_assist/lib/allbert_assist/cli/areas/threads.ex",
      "apps/allbert_assist/lib/allbert_assist/cli/ask.ex",
      "apps/allbert_assist/lib/allbert_assist/cli/channels/support.ex",
      "apps/allbert_assist/lib/allbert_assist/coding/command_grants.ex",
      "apps/allbert_assist/lib/allbert_assist/confirmations/store/agent.ex",
      "apps/allbert_assist/lib/allbert_assist/confirmations/store/persistence.ex",
      "apps/allbert_assist/lib/allbert_assist/conversations.ex",
      "apps/allbert_assist/lib/allbert_assist/dev_gates/v13_fanout_eval.ex",
      "apps/allbert_assist/lib/allbert_assist/dev_gates/v13_zero_shot_eval.ex",
      "apps/allbert_assist/lib/allbert_assist/execution/local_runner.ex",
      "apps/allbert_assist/lib/allbert_assist/execution/process_owner.ex",
      "apps/allbert_assist/lib/allbert_assist/execution/skill_script_runner.ex",
      "apps/allbert_assist/lib/allbert_assist/external/http_client.ex",
      "apps/allbert_assist/lib/allbert_assist/first_model/ollama.ex",
      "apps/allbert_assist/lib/allbert_assist/jobs/runner.ex",
      "apps/allbert_assist/lib/allbert_assist/jobs/scheduler/agent.ex",
      "apps/allbert_assist/lib/allbert_assist/jobs/scheduler/commands.ex",
      "apps/allbert_assist/lib/allbert_assist/jobs/scheduler/executor.ex",
      "apps/allbert_assist/lib/allbert_assist/mcp/registry/http.ex",
      "apps/allbert_assist/lib/allbert_assist/mcp/transport.ex",
      "apps/allbert_assist/lib/allbert_assist/objectives.ex",
      "apps/allbert_assist/lib/allbert_assist/objectives/commands.ex",
      "apps/allbert_assist/lib/allbert_assist/objectives/commands/advance_objective.ex",
      "apps/allbert_assist/lib/allbert_assist/objectives/commands/continue_objective.ex",
      "apps/allbert_assist/lib/allbert_assist/objectives/engine/agent.ex",
      "apps/allbert_assist/lib/allbert_assist/objectives/fanout.ex",
      "apps/allbert_assist/lib/allbert_assist/objectives/fanout/report_composer.ex",
      "apps/allbert_assist/lib/allbert_assist/objectives/fanout/terminal_transitions.ex",
      "apps/allbert_assist/lib/allbert_assist/objectives/lifecycle.ex",
      "apps/allbert_assist/lib/allbert_assist/objectives/runs/coordinator.ex",
      "apps/allbert_assist/lib/allbert_assist/objectives/runs/run_server.ex",
      "apps/allbert_assist/lib/allbert_assist/objectives/runs/scheduler.ex",
      "apps/allbert_assist/lib/allbert_assist/objectives/steering.ex",
      "apps/allbert_assist/lib/allbert_assist/onboarding.ex",
      "apps/allbert_assist/lib/allbert_assist/plan_build/runtime.ex",
      "apps/allbert_assist/lib/allbert_assist/public_protocol/acp/server.ex",
      "apps/allbert_assist/lib/allbert_assist/public_protocol/mcp/runtime.ex",
      "apps/allbert_assist/lib/allbert_assist/public_protocol/mcp/server.ex",
      "apps/allbert_assist/lib/allbert_assist/public_protocol/mcp/stdio_server.ex",
      "apps/allbert_assist/lib/allbert_assist/resources/grant_handoff.ex",
      "apps/allbert_assist/lib/allbert_assist/resources/grants.ex",
      "apps/allbert_assist/lib/allbert_assist/runtime.ex",
      "apps/allbert_assist/lib/allbert_assist/runtime/attach.ex",
      "apps/allbert_assist/lib/allbert_assist/runtime/attach/tui_session.ex",
      "apps/allbert_assist/lib/allbert_assist/sandbox/backends/command.ex",
      "apps/allbert_assist/lib/allbert_assist/sandbox/backends/container_runner.ex",
      "apps/allbert_assist/lib/allbert_assist/settings.ex",
      "apps/allbert_assist/lib/allbert_assist/settings/model_doctor.ex",
      "apps/allbert_assist/lib/allbert_assist/skills/direct_import.ex",
      "apps/allbert_assist/lib/allbert_assist/skills/online/registry_client.ex",
      "apps/allbert_assist/lib/allbert_assist/surfaces/context_builder.ex",
      "apps/allbert_assist/lib/allbert_assist/tools/discovery.ex",
      "apps/allbert_assist/lib/allbert_assist/tools/discovery/scan.ex",
      "apps/allbert_assist/lib/allbert_assist/voice/local_runtime/backends/ollama_stt.ex",
      "apps/allbert_assist/lib/allbert_assist/voice/provider_http.ex",
      "apps/allbert_assist/lib/mix/tasks/allbert.ask.ex",
      "apps/allbert_assist/lib/mix/tasks/allbert.delegate.ex",
      "apps/allbert_assist_web/lib/allbert_assist_web/components/layouts.ex",
      "apps/allbert_assist_web/lib/allbert_assist_web/controllers/public_protocol/mcp_http_controller.ex",
      "apps/allbert_assist_web/lib/allbert_assist_web/controllers/public_protocol/openai_controller.ex",
      "apps/allbert_assist_web/lib/allbert_assist_web/controllers/public_protocol/whatsapp_webhook_controller.ex",
      "apps/allbert_assist_web/lib/allbert_assist_web/live/jobs_live.ex",
      "apps/allbert_assist_web/lib/allbert_assist_web/live/objective_live.ex",
      "apps/allbert_assist_web/lib/allbert_assist_web/live/objectives_live.ex",
      "apps/allbert_assist_web/lib/allbert_assist_web/live/shared_shell_hooks.ex",
      "apps/allbert_assist_web/lib/allbert_assist_web/live/workspace_live.ex",
      "apps/allbert_assist_web/lib/allbert_assist_web/live_socket.ex",
      "apps/allbert_assist_web/lib/allbert_assist_web/pack_readiness.ex",
      "apps/allbert_assist_web/lib/allbert_assist_web/pack_readiness/component.ex",
      "apps/allbert_assist_web/lib/allbert_assist_web/pack_readiness/http_gate.ex",
      "apps/allbert_assist_web/lib/allbert_assist_web/surface/renderer.ex",
      "apps/allbert_assist_web/lib/allbert_assist_web/workspace/components/onboarding.ex",
      "apps/allbert_assist_web/lib/allbert_assist_web/workspace/components/operator_panels.ex",
      "apps/allbert_assist_web/lib/allbert_assist_web/workspace/components/plan_build.ex",
      "apps/allbert_assist_web/lib/allbert_assist_web/workspace/components/template_create.ex",
      "apps/allbert_assist_web/lib/allbert_assist_web/workspace/renderer.ex",
      "apps/allbert_composition/lib/allbert_assist/pack/product_cli.ex",
      "apps/allbert_email/lib/allbert_email/adapter.ex",
      "apps/allbert_email/lib/allbert_email/cli.ex",
      "apps/allbert_kernel/lib/allbert_assist/actions/runner.ex",
      "apps/allbert_notes_files/lib/allbert_notes_files/cli.ex",
      "apps/allbert_telegram/lib/allbert_telegram/adapter.ex",
      "apps/allbert_telegram/lib/allbert_telegram/cli.ex",
      "apps/allbert_telegram/lib/allbert_telegram/client.ex",
      "plugins/allbert.artifacts/lib/allbert_artifacts_web/artifact_live.ex",
      "plugins/allbert.artifacts/lib/mix/tasks/allbert.artifacts.ex",
      "plugins/allbert.browser/lib/allbert_browser/actions.ex",
      "plugins/allbert.browser/lib/allbert_browser/actions/research_handoff.ex",
      "plugins/allbert.browser/lib/allbert_browser/actions/start_session.ex",
      "plugins/allbert.browser/lib/allbert_browser/session.ex",
      "plugins/allbert.browser/lib/mix/tasks/allbert.browser.ex",
      "plugins/allbert.discord/lib/allbert_assist/channels/discord/adapter.ex",
      "plugins/allbert.discord/lib/allbert_assist/channels/discord/client.ex",
      "plugins/allbert.matrix/lib/allbert_assist/channels/matrix/adapter.ex",
      "plugins/allbert.matrix/lib/allbert_assist/channels/matrix/client.ex",
      "plugins/allbert.matrix/lib/allbert_assist/channels/matrix/doctor.ex",
      "plugins/allbert.research/lib/allbert_research/delegate_objective.ex",
      "plugins/allbert.research/lib/allbert_research/research.ex",
      "plugins/allbert.research/lib/mix/tasks/allbert.research.ex",
      "plugins/allbert.signal/lib/allbert_assist/channels/signal/adapter.ex",
      "plugins/allbert.signal/lib/allbert_assist/channels/signal/client.ex",
      "plugins/allbert.slack/lib/allbert_assist/channels/slack/adapter.ex",
      "plugins/allbert.slack/lib/allbert_assist/channels/slack/client.ex",
      "plugins/allbert.tui/lib/allbert_assist/channels/tui/adapter.ex",
      "plugins/allbert.tui/lib/allbert_assist/channels/tui/input_receipt.ex",
      "plugins/allbert.whatsapp/lib/allbert_assist/channels/whatsapp/adapter.ex",
      "plugins/allbert.whatsapp/lib/allbert_assist/channels/whatsapp/client.ex",
      "plugins/stocksage/lib/mix/tasks/stocksage.agents.ex",
      "plugins/stocksage/lib/mix/tasks/stocksage.analyses.ex",
      "plugins/stocksage/lib/mix/tasks/stocksage.analyze.ex",
      "plugins/stocksage/lib/mix/tasks/stocksage.import_sqlite.ex",
      "plugins/stocksage/lib/mix/tasks/stocksage.queue.ex",
      "plugins/stocksage/lib/stocksage/actions/run_analysis.ex",
      "plugins/stocksage/lib/stocksage/agents/native_coordinator/commands/analyze.ex",
      "plugins/stocksage/lib/stocksage/evidence.ex",
      "plugins/stocksage/lib/stocksage_web/analysis_live.ex"
    ]
  end

  defp activation_rejection_sources do
    [
      "apps/allbert_assist/lib/allbert_assist/app/registry.ex",
      "apps/allbert_assist/lib/allbert_assist/channels.ex",
      "apps/allbert_assist/lib/allbert_assist/confirmations/store/agent.ex",
      "apps/allbert_assist/lib/allbert_assist/confirmations/store/persistence.ex",
      "apps/allbert_assist/lib/allbert_assist/first_model/ollama.ex",
      "apps/allbert_assist/lib/allbert_assist/settings.ex",
      "apps/allbert_kernel/lib/allbert_assist/actions/runner.ex"
    ]
  end
end

UpdateFixture.run()
