import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
# v0.62 M1: Allbert is a localhost-serving packaged product - the phx.new
# boilerplate ("example.com" host, blanket force_ssl/HSTS that would redirect
# LAN access to a nonexistent HTTPS endpoint) is replaced. Operators fronting
# Allbert with a TLS proxy own that termination themselves.
config :allbert_assist_web, AllbertAssistWeb.Endpoint,
  url: [host: "localhost"],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configure Swoosh API Client
config :swoosh, :api_client, Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
