use std::collections::HashSet;
use std::fs;
use std::path::{Path, PathBuf};

use gray_matter::engine::YAML;
use gray_matter::Matter;
use serde::{Deserialize, Serialize};
use serde_json::Value;

use crate::error::SkillError;
use crate::intent::Intent;
use crate::{atomic_write, AllbertPaths, MemoryRoutingConfig, ModelConfig, Provider};

const INSTALL_METADATA_FILE: &str = ".allbert-install.toml";

#[derive(Debug, Clone)]
pub struct Skill {
    pub name: String,
    pub description: String,
    pub provenance: SkillProvenance,
    pub intents: Vec<Intent>,
    pub agents: Vec<ContributedAgent>,
    pub scripts: Vec<SkillScript>,
    pub allowed_tools: Vec<String>,
    pub body: String,
    pub path: PathBuf,
}

impl Skill {
    pub fn root_dir(&self) -> Result<&Path, SkillError> {
        self.path
            .parent()
            .ok_or_else(|| SkillError::Load(format!("missing parent for {}", self.path.display())))
    }
}

#[derive(Debug, Clone, Copy, Default, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "kebab-case")]
pub enum SkillProvenance {
    #[default]
    External,
    LocalPath,
    Git,
    SelfAuthored,
}

impl SkillProvenance {
    pub fn label(self) -> &'static str {
        match self {
            Self::External => "external",
            Self::LocalPath => "local-path",
            Self::Git => "git",
            Self::SelfAuthored => "self-authored",
        }
    }
}

#[derive(Debug, Clone)]
pub struct ContributedAgent {
    pub skill_name: String,
    pub short_name: String,
    pub name: String,
    pub description: String,
    pub allowed_tools: Vec<String>,
    pub model: Option<ModelConfig>,
    pub body: String,
    pub path: PathBuf,
}

#[derive(Debug, Clone)]
pub struct SkillScript {
    pub name: String,
    pub path: String,
    pub interpreter: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActiveSkill {
    pub name: String,
    pub args: Option<Value>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct InvokeSkillInput {
    pub name: String,
    #[serde(default)]
    pub args: Option<Value>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct CreateSkillInput {
    pub name: String,
    pub description: String,
    pub skip_quarantine: bool,
    #[serde(default)]
    pub allowed_tools: Vec<String>,
    pub body: String,
}

#[derive(Default)]
pub struct SkillStore {
    skills: Vec<Skill>,
}

impl SkillStore {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn discover(root: &Path) -> Self {
        let mut skills = Vec::new();
        for skill_md in find_skill_files(root) {
            if !installed_skill_enabled(&skill_md) {
                continue;
            }
            match Self::load_skill_file(&skill_md) {
                Ok(skill) => skills.push(skill),
                Err(err) => {
                    tracing::warn!("ignoring invalid skill at {}: {err}", skill_md.display());
                }
            }
        }
        skills.sort_by(|a, b| a.name.cmp(&b.name));
        Self { skills }
    }

    pub fn validate_path(path: &Path) -> Result<SkillValidationReport, SkillError> {
        let report = validate_skill_path_internal(path)?;
        Self::load_skill_file(path)?;
        Ok(report)
    }

    pub fn all(&self) -> &[Skill] {
        &self.skills
    }

    pub fn get(&self, name: &str) -> Option<&Skill> {
        self.skills.iter().find(|skill| skill.name == name)
    }

    pub fn contributed_agents(&self) -> Vec<&ContributedAgent> {
        let mut agents = self
            .skills
            .iter()
            .flat_map(|skill| skill.agents.iter())
            .collect::<Vec<_>>();
        agents.sort_by(|a, b| a.name.cmp(&b.name));
        agents
    }

    pub fn get_contributed_agent(&self, name: &str) -> Option<&ContributedAgent> {
        self.skills
            .iter()
            .flat_map(|skill| skill.agents.iter())
            .find(|agent| agent.name == name)
    }

    pub fn get_script(
        &self,
        skill_name: &str,
        script_name: &str,
    ) -> Option<(&Skill, &SkillScript)> {
        let skill = self.get(skill_name)?;
        let script = skill
            .scripts
            .iter()
            .find(|script| script.name == script_name)?;
        Some((skill, script))
    }

    pub fn render_agents_markdown(&self) -> String {
        self.render_agents_markdown_with_routing(&MemoryRoutingConfig::default())
    }

    pub fn render_agents_markdown_with_routing(&self, routing: &MemoryRoutingConfig) -> String {
        let mut sections = vec![
            "<!-- This file is generated by Allbert. Do not edit it directly. Edit skill files and refresh the skill catalog instead. -->".to_string(),
            "# AGENTS".to_string(),
            String::new(),
            "## allbert/root".to_string(),
            "- description: Default root agent for the current session.".to_string(),
            "- contributing skill: (kernel)".to_string(),
            "- allowed-tools: session default".to_string(),
            "- model override: none".to_string(),
        ];

        sections.push(String::new());
        sections.push("## Skills".to_string());
        if self.skills.is_empty() {
            sections.push("- (none)".to_string());
        } else {
            for skill in &self.skills {
                sections.push(format!(
                    "- {}: {} (provenance: {}; allowed-tools: {})",
                    skill.name,
                    skill.description,
                    skill.provenance.label(),
                    if skill.allowed_tools.is_empty() {
                        "none".into()
                    } else {
                        skill.allowed_tools.join(", ")
                    }
                ));
            }
        }

        for agent in self.contributed_agents() {
            sections.push(String::new());
            sections.push(format!("## {}", agent.name));
            sections.push(format!("- description: {}", agent.description));
            sections.push(format!("- contributing skill: {}", agent.skill_name));
            sections.push(format!(
                "- allowed-tools: {}",
                if agent.allowed_tools.is_empty() {
                    "(none)".into()
                } else {
                    agent.allowed_tools.join(", ")
                }
            ));
            sections.push(format!(
                "- model override: {}",
                match &agent.model {
                    Some(model) => format!("{:?} / {}", model.provider, model.model_id),
                    None => "none".into(),
                }
            ));
        }

        sections.push(String::new());
        sections.push("## Routing".to_string());
        sections.push(format!("- mode: {}", routing.mode.label()));
        sections.push(format!(
            "- always-eligible skills: {}",
            render_csv(&routing.always_eligible_skills)
        ));
        sections.push(format!(
            "- auto-activate intents: {}",
            render_csv(&routing.auto_activate_intents)
        ));
        sections.push(format!(
            "- auto-activate cues: {}",
            render_csv(&routing.auto_activate_cues)
        ));

        sections.push(String::new());
        sections.join("\n")
    }

    pub fn routing_prompt(&self, routing: &MemoryRoutingConfig) -> String {
        let lines = routing
            .always_eligible_skills
            .iter()
            .filter_map(|name| {
                self.get(name)
                    .map(|skill| format!("- {}: {}", skill.name, skill.description))
            })
            .collect::<Vec<_>>();
        if lines.is_empty() {
            String::new()
        } else {
            lines.join("\n")
        }
    }

    pub fn upsert_active_skill(
        active_skills: &mut Vec<ActiveSkill>,
        name: &str,
        args: Option<Value>,
    ) {
        if let Some(existing) = active_skills.iter_mut().find(|skill| skill.name == name) {
            existing.args = args;
            return;
        }
        active_skills.push(ActiveSkill {
            name: name.into(),
            args,
        });
    }

    pub fn allowed_tool_union(&self, active_skills: &[ActiveSkill]) -> Option<HashSet<String>> {
        if active_skills.is_empty() {
            return None;
        }

        let mut allowed = HashSet::new();
        for active in active_skills {
            if let Some(skill) = self.get(&active.name) {
                allowed.extend(skill.allowed_tools.iter().cloned());
            }
        }
        Some(allowed)
    }

    pub fn create(
        &mut self,
        skills_root: &Path,
        name: &str,
        description: &str,
        allowed_tools: &[String],
        body: &str,
        provenance: SkillProvenance,
    ) -> Result<Skill, SkillError> {
        validate_strict_skill_name(name)?;
        let skill_dir = skills_root.join(name);
        let skill_path = skill_dir.join("SKILL.md");
        fs::create_dir_all(&skill_dir)
            .map_err(|err| SkillError::Load(format!("create {}: {err}", skill_dir.display())))?;

        let mut frontmatter = String::new();
        frontmatter.push_str("---\n");
        frontmatter.push_str(&format!("name: {}\n", name));
        frontmatter.push_str(&format!("description: {}\n", yaml_quote(description)));
        frontmatter.push_str(&format!("provenance: {}\n", provenance.label()));
        if !allowed_tools.is_empty() {
            frontmatter.push_str("allowed-tools: ");
            frontmatter.push_str(&allowed_tools.join(" "));
            frontmatter.push('\n');
        }
        frontmatter.push_str("---\n\n");
        frontmatter.push_str(body.trim_end());
        frontmatter.push('\n');

        atomic_write(&skill_path, frontmatter.as_bytes())
            .map_err(|err| SkillError::Load(format!("write {}: {err}", skill_path.display())))?;
        let skill = Self::load_skill_file(&skill_path)?;
        self.replace(skill.clone());
        Ok(skill)
    }

    pub fn manifest_prompt(&self) -> String {
        if self.skills.is_empty() {
            return "No skills are currently installed.".into();
        }

        self.skills
            .iter()
            .map(|skill| {
                format!(
                    "- {}: {} (provenance: {}; allowed-tools: {})",
                    skill.name,
                    skill.description,
                    skill.provenance.label(),
                    if skill.allowed_tools.is_empty() {
                        "none".into()
                    } else {
                        skill.allowed_tools.join(", ")
                    }
                )
            })
            .collect::<Vec<_>>()
            .join("\n")
    }

    pub fn catalog_skill_names(&self) -> Vec<String> {
        self.skills.iter().map(|skill| skill.name.clone()).collect()
    }

    pub fn intent_hint_prompt(&self, intent: &Intent) -> Option<String> {
        let mut relevant = self
            .skills
            .iter()
            .filter(|skill| skill.intents.contains(intent))
            .map(|skill| format!("- {}: {}", skill.name, skill.description))
            .collect::<Vec<_>>();

        if relevant.is_empty() {
            let keywords: &[&str] = match intent {
                Intent::Task => &["task", "write", "note", "capture", "review"],
                Intent::Chat => &[],
                Intent::Schedule => &["schedule", "job", "review", "recurring", "daily", "weekly"],
                Intent::MemoryQuery => &["memory", "note", "recall", "remember", "capture"],
                Intent::Meta => &["help", "status", "model", "config", "assistant"],
            };

            if keywords.is_empty() {
                return None;
            }

            relevant = self
                .skills
                .iter()
                .filter(|skill| {
                    let haystack = format!(
                        "{} {}",
                        skill.name.to_ascii_lowercase(),
                        skill.description.to_ascii_lowercase()
                    );
                    keywords.iter().any(|keyword| haystack.contains(keyword))
                })
                .map(|skill| format!("- {}: {}", skill.name, skill.description))
                .collect::<Vec<_>>();
        }

        if relevant.is_empty() {
            None
        } else {
            Some(relevant.join("\n"))
        }
    }

    pub fn active_prompt(
        &self,
        active_skills: &[ActiveSkill],
        max_skill_args_bytes: usize,
    ) -> String {
        let mut blocks = Vec::new();
        for active in active_skills {
            let Some(skill) = self.get(&active.name) else {
                continue;
            };
            tracing::info!(
                skill = %skill.name,
                provenance = skill.provenance.label(),
                "activating skill"
            );
            let mut block = format!("### Skill: {}\n{}\n", skill.name, skill.body.trim());
            if let Some(args) = &active.args {
                let serialized = serde_json::to_string_pretty(args).unwrap_or_else(|_| "{}".into());
                let truncated = truncate_to_bytes(&serialized, max_skill_args_bytes);
                block = format!(
                    "### Skill: {}\nInvocation arguments (JSON):\n{}\n\n{}",
                    skill.name,
                    truncated,
                    skill.body.trim()
                );
            }
            blocks.push(block);
        }
        blocks.join("\n\n")
    }

    pub fn activated_skill_names(&self, active_skills: &[ActiveSkill]) -> Vec<String> {
        active_skills
            .iter()
            .filter_map(|active| self.get(&active.name).map(|skill| skill.name.clone()))
            .collect()
    }

    pub fn read_reference(
        &self,
        skill_name: &str,
        relative: &str,
        max_bytes: Option<usize>,
    ) -> Result<String, SkillError> {
        let skill = self
            .get(skill_name)
            .ok_or_else(|| SkillError::NotFound(skill_name.into()))?;
        let path = resolve_resource_path(skill.root_dir()?, relative)?;
        let raw = fs::read_to_string(&path)
            .map_err(|err| SkillError::Load(format!("read {}: {err}", path.display())))?;
        Ok(match max_bytes {
            Some(limit) => truncate_to_bytes(&raw, limit),
            None => raw,
        })
    }

    pub fn resolve_script(
        &self,
        skill_name: &str,
        script_name: &str,
    ) -> Result<ResolvedSkillScript, SkillError> {
        let (skill, script) = self
            .get_script(skill_name, script_name)
            .ok_or_else(|| SkillError::NotFound(format!("{skill_name}/{script_name}")))?;
        let path = resolve_declared_child_path(skill.root_dir()?, &script.path, "scripts")?;
        Ok(ResolvedSkillScript {
            skill_name: skill.name.clone(),
            script_name: script.name.clone(),
            interpreter: script.interpreter.clone(),
            declared_path: script.path.clone(),
            path,
        })
    }

    fn replace(&mut self, skill: Skill) {
        if let Some(index) = self
            .skills
            .iter()
            .position(|existing| existing.name == skill.name)
        {
            self.skills[index] = skill;
        } else {
            self.skills.push(skill);
            self.skills.sort_by(|a, b| a.name.cmp(&b.name));
        }
    }

    fn load_skill_file(path: &Path) -> Result<Skill, SkillError> {
        let raw = fs::read_to_string(path)
            .map_err(|err| SkillError::Load(format!("read {}: {err}", path.display())))?;
        let matter = Matter::<YAML>::new();
        let parsed = matter
            .parse::<Frontmatter>(&raw)
            .map_err(|err| SkillError::Load(format!("parse {}: {err}", path.display())))?;
        let data = parsed.data.ok_or_else(|| {
            SkillError::Load(format!("missing frontmatter in {}", path.display()))
        })?;

        validate_skill_path_internal(path)?;

        Ok(Skill {
            agents: load_skill_agents(path, &data.name, &data.agents)?,
            intents: data.intents.normalize()?,
            scripts: data.scripts.normalize()?,
            name: data.name,
            description: data.description,
            provenance: data.provenance,
            allowed_tools: data.allowed_tools.normalize(),
            body: parsed.content.trim().to_string(),
            path: path.to_path_buf(),
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SkillValidationReport {
    pub name: String,
    pub path: PathBuf,
    pub scripts: usize,
    pub agents: usize,
}

#[derive(Debug, Clone)]
pub struct ResolvedSkillScript {
    pub skill_name: String,
    pub script_name: String,
    pub interpreter: String,
    pub declared_path: String,
    pub path: PathBuf,
}

#[derive(Debug, Deserialize)]
struct Frontmatter {
    name: String,
    description: String,
    #[serde(default)]
    #[allow(dead_code)]
    provenance: SkillProvenance,
    #[serde(default)]
    intents: IntentList,
    #[serde(default)]
    agents: AgentContributions,
    #[serde(default)]
    scripts: ScriptEntries,
    #[serde(rename = "allowed-tools", default)]
    allowed_tools: AllowedTools,
}

#[derive(Debug, Deserialize)]
struct ValidationFrontmatter {
    name: String,
    description: String,
    #[serde(default)]
    #[allow(dead_code)]
    provenance: SkillProvenance,
    #[serde(default)]
    compatibility: Option<CompatibilityFrontmatter>,
    #[serde(default)]
    metadata: Option<serde_json::Value>,
    #[serde(default)]
    license: Option<String>,
    #[serde(default)]
    intents: IntentList,
    #[serde(default)]
    agents: AgentContributions,
    #[serde(default)]
    scripts: ScriptEntries,
    #[serde(rename = "allowed-tools", default)]
    allowed_tools: AllowedTools,
}

#[derive(Debug, Deserialize)]
struct InstallMetadata {
    #[serde(default = "default_enabled")]
    enabled: bool,
}

fn default_enabled() -> bool {
    true
}

#[allow(dead_code)]
#[derive(Debug, Deserialize)]
struct CompatibilityFrontmatter {
    #[serde(default)]
    agentskills: Option<String>,
    #[serde(default)]
    allbert: Option<String>,
}

#[derive(Debug, Default, Deserialize)]
#[serde(untagged)]
enum ScriptEntries {
    #[default]
    Missing,
    Entries(Vec<ScriptEntry>),
}

#[derive(Debug, Deserialize)]
struct ScriptEntry {
    name: String,
    path: String,
    interpreter: String,
}

#[derive(Debug, Default, Deserialize)]
#[serde(untagged)]
enum IntentList {
    #[default]
    Missing,
    One(String),
    Many(Vec<String>),
}

impl IntentList {
    fn normalize(self) -> Result<Vec<Intent>, SkillError> {
        let values = match self {
            Self::Missing => Vec::new(),
            Self::One(value) => vec![value],
            Self::Many(values) => values,
        };
        values
            .into_iter()
            .map(|value| {
                Intent::parse(&value)
                    .ok_or_else(|| SkillError::Load(format!("unknown skill intent: {value}")))
            })
            .collect()
    }
}

#[derive(Debug, Default, Deserialize)]
#[serde(untagged)]
enum AgentContributions {
    #[default]
    Missing,
    Paths(Vec<String>),
    Entries(Vec<AgentContributionEntry>),
}

impl AgentContributions {
    fn normalize(&self) -> Vec<String> {
        match self {
            Self::Missing => Vec::new(),
            Self::Paths(paths) => paths.clone(),
            Self::Entries(entries) => entries.iter().map(|entry| entry.path.clone()).collect(),
        }
    }
}

impl ScriptEntries {
    fn entries(&self) -> &[ScriptEntry] {
        match self {
            Self::Missing => &[],
            Self::Entries(entries) => entries,
        }
    }

    fn normalize(&self) -> Result<Vec<SkillScript>, SkillError> {
        self.entries()
            .iter()
            .map(|entry| {
                validate_strict_skill_name(&entry.name)?;
                if entry.interpreter.trim().is_empty() {
                    return Err(SkillError::Load(format!(
                        "script '{}' is missing an interpreter",
                        entry.name
                    )));
                }
                Ok(SkillScript {
                    name: entry.name.clone(),
                    path: entry.path.clone(),
                    interpreter: entry.interpreter.clone(),
                })
            })
            .collect()
    }
}

#[derive(Debug, Deserialize)]
struct AgentContributionEntry {
    path: String,
}

#[derive(Debug, Deserialize)]
struct AgentFrontmatter {
    name: String,
    description: String,
    #[serde(rename = "allowed-tools", default)]
    allowed_tools: AllowedTools,
    #[serde(default)]
    model: Option<AgentModelFrontmatter>,
}

#[derive(Debug, Deserialize)]
struct AgentModelFrontmatter {
    provider: Provider,
    model_id: String,
    #[serde(default)]
    api_key_env: Option<String>,
    #[serde(default)]
    base_url: Option<String>,
    max_tokens: u32,
}

#[derive(Debug, Default, Deserialize)]
#[serde(untagged)]
enum AllowedTools {
    #[default]
    Missing,
    String(String),
    List(Vec<String>),
}

fn load_skill_agents(
    skill_path: &Path,
    skill_name: &str,
    contributions: &AgentContributions,
) -> Result<Vec<ContributedAgent>, SkillError> {
    let matter = Matter::<YAML>::new();
    let base_dir = skill_path
        .parent()
        .ok_or_else(|| SkillError::Load(format!("missing parent for {}", skill_path.display())))?;
    let mut agents = Vec::new();
    for relative in contributions.normalize() {
        let path = base_dir.join(&relative);
        let raw = fs::read_to_string(&path)
            .map_err(|err| SkillError::Load(format!("read {}: {err}", path.display())))?;
        let parsed = matter
            .parse::<AgentFrontmatter>(&raw)
            .map_err(|err| SkillError::Load(format!("parse {}: {err}", path.display())))?;
        let data = parsed.data.ok_or_else(|| {
            SkillError::Load(format!("missing frontmatter in {}", path.display()))
        })?;
        validate_strict_skill_name(&data.name)?;
        let namespaced = format!("{skill_name}/{}", data.name);
        agents.push(ContributedAgent {
            skill_name: skill_name.into(),
            short_name: data.name.clone(),
            name: namespaced,
            description: data.description,
            allowed_tools: data.allowed_tools.normalize(),
            model: data.model.map(|model| ModelConfig {
                provider: model.provider,
                model_id: model.model_id,
                api_key_env: model.api_key_env,
                base_url: model.base_url,
                max_tokens: model.max_tokens,
                context_window_tokens: 0,
            }),
            body: parsed.content.trim().to_string(),
            path,
        });
    }
    agents.sort_by(|a, b| a.name.cmp(&b.name));
    Ok(agents)
}

impl AllowedTools {
    fn normalize(self) -> Vec<String> {
        match self {
            Self::Missing => Vec::new(),
            Self::String(raw) => raw
                .split_whitespace()
                .map(|tool| tool.to_string())
                .collect(),
            Self::List(values) => values,
        }
    }
}

fn find_skill_files(root: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    let installed_root = root.join("installed");
    collect_immediate_skill_files(&installed_root, &mut out);
    out
}

fn collect_immediate_skill_files(root: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(root) else {
        return;
    };

    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            let skill_md = path.join("SKILL.md");
            if skill_md.exists() {
                out.push(skill_md);
            }
        }
    }
}

fn installed_skill_enabled(skill_md: &Path) -> bool {
    let Some(skill_dir) = skill_md.parent() else {
        return true;
    };
    let metadata_path = skill_dir.join(INSTALL_METADATA_FILE);
    let Ok(raw) = fs::read_to_string(&metadata_path) else {
        return true;
    };
    match toml::from_str::<InstallMetadata>(&raw) {
        Ok(metadata) => metadata.enabled,
        Err(err) => {
            tracing::warn!(
                path = %metadata_path.display(),
                "ignoring invalid skill install metadata while discovering skills: {err}"
            );
            true
        }
    }
}

fn validate_strict_skill_name(name: &str) -> Result<(), SkillError> {
    if name.is_empty() {
        return Err(SkillError::Load("skill name cannot be empty".into()));
    }
    if name.len() > 64 {
        return Err(SkillError::Load("skill name is too long".into()));
    }
    if name
        .chars()
        .all(|ch| ch.is_ascii_lowercase() || ch.is_ascii_digit() || ch == '-')
        && !name.starts_with('-')
        && !name.ends_with('-')
        && !name.contains("--")
    {
        Ok(())
    } else {
        Err(SkillError::Load(format!(
            "skill name '{}' must be kebab-case",
            name
        )))
    }
}

fn validate_skill_path_internal(path: &Path) -> Result<SkillValidationReport, SkillError> {
    if path
        .file_name()
        .and_then(|name| name.to_str())
        .is_none_or(|name| !name.eq_ignore_ascii_case("SKILL.md"))
    {
        return Err(SkillError::Load(format!(
            "expected a SKILL.md file, got {}",
            path.display()
        )));
    }

    let raw = fs::read_to_string(path)
        .map_err(|err| SkillError::Load(format!("read {}: {err}", path.display())))?;
    let matter = Matter::<YAML>::new();
    let parsed = matter
        .parse::<ValidationFrontmatter>(&raw)
        .map_err(|err| SkillError::Load(format!("parse {}: {err}", path.display())))?;
    let data = parsed
        .data
        .ok_or_else(|| SkillError::Load(format!("missing frontmatter in {}", path.display())))?;

    validate_strict_skill_name(&data.name)?;
    if data.description.trim().is_empty() {
        return Err(SkillError::Load(format!(
            "missing description in {}",
            path.display()
        )));
    }
    if data.description.chars().count() > 1024 {
        return Err(SkillError::Load(format!(
            "description is too long in {}",
            path.display()
        )));
    }

    let skill_dir = path
        .parent()
        .ok_or_else(|| SkillError::Load(format!("missing parent for {}", path.display())))?;
    let dir_name = skill_dir
        .file_name()
        .and_then(|name| name.to_str())
        .ok_or_else(|| {
            SkillError::Load(format!("invalid skill directory {}", skill_dir.display()))
        })?;
    if dir_name != data.name {
        return Err(SkillError::Load(format!(
            "skill directory '{}' does not match frontmatter name '{}'",
            dir_name, data.name
        )));
    }

    let _ = data.intents.normalize()?;
    let _ = data.allowed_tools.normalize();
    let _ = data.metadata;
    let _ = data.license;
    let _ = data.compatibility;

    for relative in data.agents.normalize() {
        validate_relative_child_path(skill_dir, &relative, "agents")?;
    }
    for script in data.scripts.entries() {
        validate_strict_skill_name(&script.name)?;
        if script.interpreter.trim().is_empty() {
            return Err(SkillError::Load(format!(
                "script '{}' is missing an interpreter in {}",
                script.name,
                path.display()
            )));
        }
        validate_relative_child_path(skill_dir, &script.path, "scripts")?;
    }

    Ok(SkillValidationReport {
        name: data.name,
        path: path.to_path_buf(),
        scripts: data.scripts.entries().len(),
        agents: data.agents.normalize().len(),
    })
}

fn validate_relative_child_path(
    skill_dir: &Path,
    relative: &str,
    expected_prefix: &str,
) -> Result<(), SkillError> {
    let resolved = resolve_declared_child_path(skill_dir, relative, expected_prefix)?;
    if !resolved.exists() {
        return Err(SkillError::Load(format!(
            "referenced path '{}' does not exist for {}",
            relative,
            skill_dir.display()
        )));
    }
    Ok(())
}

fn resolve_declared_child_path(
    skill_dir: &Path,
    relative: &str,
    expected_prefix: &str,
) -> Result<PathBuf, SkillError> {
    let relative_path = Path::new(relative);
    if relative_path.is_absolute()
        || relative_path
            .components()
            .any(|component| matches!(component, std::path::Component::ParentDir))
    {
        return Err(SkillError::Load(format!(
            "path '{}' must stay inside the skill directory",
            relative
        )));
    }
    if relative_path
        .components()
        .next()
        .and_then(|component| match component {
            std::path::Component::Normal(value) => value.to_str(),
            _ => None,
        })
        .is_none_or(|value| value != expected_prefix)
    {
        return Err(SkillError::Load(format!(
            "path '{}' must live under {}/",
            relative, expected_prefix
        )));
    }
    Ok(skill_dir.join(relative_path))
}

fn resolve_resource_path(skill_dir: &Path, relative: &str) -> Result<PathBuf, SkillError> {
    let relative_path = Path::new(relative);
    let Some(prefix) = relative_path
        .components()
        .next()
        .and_then(|component| match component {
            std::path::Component::Normal(value) => value.to_str(),
            _ => None,
        })
    else {
        return Err(SkillError::Load("resource path cannot be empty".into()));
    };

    if prefix != "references" && prefix != "assets" {
        return Err(SkillError::Load(format!(
            "resource path '{}' must live under references/ or assets/",
            relative
        )));
    }

    let resolved = resolve_declared_child_path(skill_dir, relative, prefix)?;
    if !resolved.exists() {
        return Err(SkillError::Load(format!(
            "resource path '{}' does not exist for {}",
            relative,
            skill_dir.display()
        )));
    }
    if !resolved.is_file() {
        return Err(SkillError::Load(format!(
            "resource path '{}' is not a file",
            relative
        )));
    }
    Ok(resolved)
}

fn yaml_quote(value: &str) -> String {
    format!("{value:?}")
}

fn truncate_to_bytes(input: &str, max_bytes: usize) -> String {
    if input.len() <= max_bytes {
        return input.to_string();
    }

    let mut end = max_bytes;
    while end > 0 && !input.is_char_boundary(end) {
        end -= 1;
    }
    input[..end].to_string()
}

fn render_csv(values: &[String]) -> String {
    if values.is_empty() {
        "(none)".into()
    } else {
        values.join(", ")
    }
}

pub fn validate_skill_path(path: &Path) -> Result<SkillValidationReport, SkillError> {
    SkillStore::validate_path(path)
}

pub fn refresh_agents_markdown(paths: &AllbertPaths) -> Result<String, SkillError> {
    let store = SkillStore::discover(&paths.skills);
    let rendered = store.render_agents_markdown();
    atomic_write(&paths.agents_notes, rendered.as_bytes()).map_err(|err| {
        SkillError::Load(format!("write {}: {err}", paths.agents_notes.display()))
    })?;
    Ok(rendered)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_dir(name: &str) -> PathBuf {
        let unique = format!("allbert-skills-{}-{}", std::process::id(), name);
        let path = std::env::temp_dir().join(unique);
        let _ = fs::remove_dir_all(&path);
        fs::create_dir_all(&path).unwrap();
        path
    }

    fn write_skill(path: &Path, raw: &str) {
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(path, raw).unwrap();
    }

    #[test]
    fn strict_validation_accepts_agentskills_layout() {
        let root = temp_dir("strict");
        let skill_dir = root.join("research-helper");
        fs::create_dir_all(skill_dir.join("scripts")).unwrap();
        fs::create_dir_all(skill_dir.join("agents")).unwrap();
        fs::write(skill_dir.join("scripts/summarize.py"), "print('ok')").unwrap();
        fs::write(
            skill_dir.join("agents/researcher.md"),
            "---\nname: researcher\ndescription: Focused reader.\n---\n\nRead carefully.\n",
        )
        .unwrap();
        write_skill(
            &skill_dir.join("SKILL.md"),
            "---\nname: research-helper\ndescription: Helps with research.\nintents: [task]\nagents:\n  - path: agents/researcher.md\nscripts:\n  - name: summarize\n    path: scripts/summarize.py\n    interpreter: python\n---\n\n# Research Helper\n",
        );

        let report = validate_skill_path(&skill_dir.join("SKILL.md")).unwrap();
        assert_eq!(report.name, "research-helper");
        assert_eq!(report.scripts, 1);
        assert_eq!(report.agents, 1);

        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn discovery_reads_installed_root_and_ignores_incoming() {
        let root = temp_dir("discover");
        let skills_root = root.join("skills");
        let installed_root = skills_root.join("installed");
        let incoming_root = skills_root.join("incoming");
        write_skill(
            &installed_root.join("installed-skill/SKILL.md"),
            "---\nname: installed-skill\ndescription: Installed.\ncompatibility:\n  agentskills: \">=0.1\"\n  allbert: \">=0.4\"\nmetadata:\n  tags: [test]\n---\n\ninstalled\n",
        );
        write_skill(
            &incoming_root.join("incoming-skill/SKILL.md"),
            "---\nname: incoming-skill\ndescription: Incoming.\ncompatibility:\n  agentskills: \">=0.1\"\n  allbert: \">=0.4\"\nmetadata:\n  tags: [test]\n---\n\nincoming\n",
        );

        let store = SkillStore::discover(&skills_root);
        assert_eq!(store.all().len(), 1);
        assert_eq!(
            store.get("installed-skill").unwrap().description,
            "Installed."
        );
        assert_eq!(
            store.get("installed-skill").unwrap().provenance,
            SkillProvenance::External
        );
        assert!(store.get("incoming-skill").is_none());

        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn discovery_ignores_disabled_installed_skills() {
        let root = temp_dir("disabled");
        let skills_root = root.join("skills");
        let installed_root = skills_root.join("installed");
        write_skill(
            &installed_root.join("enabled-skill/SKILL.md"),
            "---\nname: enabled-skill\ndescription: Enabled.\n---\n\nenabled\n",
        );
        write_skill(
            &installed_root.join("disabled-skill/SKILL.md"),
            "---\nname: disabled-skill\ndescription: Disabled.\n---\n\ndisabled\n",
        );
        fs::write(
            installed_root.join("disabled-skill/.allbert-install.toml"),
            r#"
enabled = false
tree_sha256 = "abc"
approved_at = "2026-04-25T00:00:00Z"
installed_at = "2026-04-25T00:00:00Z"

[source]
kind = "local_path"
identity = "/tmp/disabled-skill"
requested_ref = ""
"#,
        )
        .unwrap();

        let store = SkillStore::discover(&skills_root);
        assert!(store.get("enabled-skill").is_some());
        assert!(store.get("disabled-skill").is_none());

        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn frontmatter_provenance_defaults_and_parses() {
        let root = temp_dir("provenance");
        let skills_root = root.join("skills/installed");
        write_skill(
            &skills_root.join("external-skill/SKILL.md"),
            "---\nname: external-skill\ndescription: Missing provenance.\n---\n\nbody\n",
        );
        write_skill(
            &skills_root.join("authored-skill/SKILL.md"),
            "---\nname: authored-skill\ndescription: Authored.\nprovenance: self-authored\n---\n\nbody\n",
        );

        let store = SkillStore::discover(&root.join("skills"));

        assert_eq!(
            store.get("external-skill").unwrap().provenance,
            SkillProvenance::External
        );
        assert_eq!(
            store.get("authored-skill").unwrap().provenance,
            SkillProvenance::SelfAuthored
        );

        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn strict_validation_rejects_non_kebab_name() {
        let root = temp_dir("invalid");
        let skill_dir = root.join("BadSkill");
        write_skill(
            &skill_dir.join("SKILL.md"),
            "---\nname: BadSkill\ndescription: Invalid.\n---\n\nbody\n",
        );

        let err = validate_skill_path(&skill_dir.join("SKILL.md")).unwrap_err();
        assert!(err.to_string().contains("kebab-case"));

        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn shipped_example_note_taker_validates_cleanly() {
        let skill_md = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../examples/skills/note-taker/SKILL.md")
            .canonicalize()
            .expect("example skill should resolve");

        let report = validate_skill_path(&skill_md).expect("example skill should validate");
        assert_eq!(report.name, "note-taker");
        assert_eq!(report.scripts, 1);
        assert_eq!(report.agents, 0);
    }
}
